"""'initial'

Revision ID: 123aad10edd4
Revises: 7245141a15f7
Create Date: 2025-03-29 19:20:59.256312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123aad10edd4'
down_revision: Union[str, None] = '7245141a15f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.add_column('statements', sa.Column('recipient', sa.String(length=255), nullable=True))
    op.add_column('statements', sa.Column('anonymous', sa.Boolean(), nullable=True))
    op.add_column('statements', sa.Column('policeman_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'statements', 'policemans', ['policeman_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_column('statements', 'policeman_id')
    op.drop_column('statements', 'anonymous')
    op.drop_column('statements', 'recipient')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
