"""delete video mailing

Revision ID: 448030b7cad4
Revises: 603deb97eb21
Create Date: 2025-03-30 11:02:31.428947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448030b7cad4'
down_revision: Union[str, None] = '603deb97eb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('mailings', 'video')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('video', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('mailings', 'description')
    # ### end Alembic commands ###
