"""create models

Revision ID: faa37e79bbb7
Revises: 
Create Date: 2025-03-28 15:49:26.853017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'faa37e79bbb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)

    op.create_table('crimes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('data', sa.String(length=255), nullable=True),
        sa.Column('street', sa.String(length=255), nullable=True),
        sa.Column('geoposition', sa.String(length=255), nullable=True),
        sa.Column('period', sa.String(length=255), nullable=True),
        sa.Column('stat', sa.String(length=255), nullable=True),
        sa.Column('time_period', sa.String(length=255), nullable=True),
        sa.Column('organ', sa.String(length=255), nullable=True),
        sa.Column('year', sa.String(length=255), nullable=True),
        sa.Column('crime_code', sa.String(length=255), nullable=True),
        sa.Column('hard_code', sa.String(length=255), nullable=True),
        sa.Column('city_code', sa.String(length=255), nullable=True),
        sa.Column('ud', sa.String(length=255), nullable=True),
        sa.Column('objectid', sa.String(length=255), nullable=True),
        sa.Column('home_number', sa.String(length=255), nullable=True),
        sa.Column('reg_code', sa.String(length=255), nullable=True),
        sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # Добавляем проверку на существование индекса перед его созданием
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 
                FROM pg_indexes 
                WHERE schemaname = 'public' 
                AND indexname = 'idx_crimes_geom'
            ) THEN
                EXECUTE 'CREATE INDEX idx_crimes_geom ON crimes USING gist (geom)';
            END IF;
        END$$;
    """)
    op.create_index(op.f('ix_crimes_id'), 'crimes', ['id'], unique=False)

    op.create_table('geolocations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('city', sa.String(length=255), nullable=True),
        sa.Column('street', sa.String(length=255), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geolocations_id'), 'geolocations', ['id'], unique=False)

    op.create_table('ranks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranks_id'), 'ranks', ['id'], unique=False)

    op.create_table('status_call',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('status_name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_call_id'), 'status_call', ['id'], unique=False)

    op.create_table('types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type_name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_types_id'), 'types', ['id'], unique=False)

    op.create_table('stations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('station_name', sa.String(length=100), nullable=False),
        sa.Column('geolocation_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['geolocation_id'], ['geolocations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)

    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=True),
        sa.Column('last_name', sa.String(length=50), nullable=True),
        sa.Column('uin', sa.String(length=12), nullable=True),
        sa.Column('email', sa.String(length=50), nullable=True),
        sa.Column('phone_number', sa.String(length=30), nullable=True),
        sa.Column('password', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('verification_code', sa.String(length=6), nullable=True),
        sa.Column('birth_day', sa.DateTime(), nullable=True),
        sa.Column('gender', sa.String(length=20), nullable=True),
        sa.Column('photo', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('geolocation_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['geolocation_id'], ['geolocations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    op.create_table('policemans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(length=50), nullable=True),
        sa.Column('last_name', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=50), nullable=True),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('photo', sa.String(length=255), nullable=True),
        sa.Column('birth_day', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('verification_code', sa.String(length=6), nullable=True),
        sa.Column('resume', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('rank_id', sa.Integer(), nullable=True),
        sa.Column('station_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_policemans_id'), 'policemans', ['id'], unique=False)

    op.create_table('statements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('type_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['type_id'], ['types.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_id'), 'statements', ['id'], unique=False)

    op.create_table('chats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('policeman_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['policeman_id'], ['policemans.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)

    op.create_table('session_calls',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('policeman_id', sa.Integer(), nullable=True),
        sa.Column('call_status_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['call_status_id'], ['status_call.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['policeman_id'], ['policemans.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_calls_id'), 'session_calls', ['id'], unique=False)

    op.create_table('messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_session_calls_id'), table_name='session_calls')
    op.drop_table('session_calls')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_statements_id'), table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_policemans_id'), table_name='policemans')
    op.drop_table('policemans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_types_id'), table_name='types')
    op.drop_table('types')
    op.drop_index(op.f('ix_status_call_id'), table_name='status_call')
    op.drop_table('status_call')
    op.drop_index(op.f('ix_ranks_id'), table_name='ranks')
    op.drop_table('ranks')
    op.drop_index(op.f('ix_geolocations_id'), table_name='geolocations')
    op.drop_table('geolocations')
    op.drop_index(op.f('ix_crimes_id'), table_name='crimes')
    op.drop_index('idx_crimes_geom', table_name='crimes', postgresql_using='gist')
    op.drop_table('crimes')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###